console.log('loaded');

let btnText = document.querySelector('.btn-text');
let i=0;

btnText.addEventListener('click', function(){
    let texts = ['He’s a 10 but he’s immature',
        'He’s a 10 but he’s always late',
        'He’s a 10 but he’s clingy',
        'He’s a 10 but he’s rude to service staff',
        'He’s a 9 but he has poor hygiene',
        'He’s a 10 but talks about his ex a lot',
        'He’s a 4 but he dresses well',
        'He’s a 10 but he acts entitled',
        'He’s a 10 but most of his friends are girls',
        'He’s a 3 but he tips well',
       ' He’s a 10 but he calls you mommy',
       ' He’s a 6 but he has a car and can drive',
        'He’s a 10 but he has no sense of humor',
       ' He’s a 10 but he follows a bunch of random Instagram models',
        'He’s a 4 but he has good music taste',
        'He’s a 10 but he follows girls that don’t follow him back',
        'He’s a 10 but he doesn’t argue back',
        'He’s a 10 but he has no ambition',
        'He’s a 6 but he has no social media',
        'He’s a 10 but he cheated before',
        'He’s a 10 but he wears a fanny pack',
       ' He’s a 10 but he acts like a baby when he doesn’t get what he wants',
       ' He’s a 5 but he’s organized',
        'He’s a 10 but his place is a total mess',
        'He’s a 10 but is still hung up on his ex',
        'He’s a 6 but he remembers everything about you',
        'He’s a 10 but he’s shorter than you',
        'He’s a 9 but he’s terrified of bugs',
        'He’s a 10 but he’s constantly talking about himself',
       ' He’s a 5 but he has a good sense of direction',
        'He’s a 10 but he refuses to post you on Instagram',
        'He’s a 10 but he uses the “🥺” emoji',
        'He’s an 8 but he doesn’t workout',
        'He’s a 10 but he asks you to split the bill on the first date',
        'He’s a 10 but he vapes',
        'He’s a 3 but he hates the same things as you',
        'He’s a 10 but he starts every conversation with “wyd”',
        'He’s a 10 but he calls other girls hot',
        'He’s a 5 but he’s a good listener',
        'He’s a 10 but he’s disrespectful to his parents',
        'He’s a 10 but his best friend is his ex',
       ' He’s a 9 but he still uses Snapchat to communicate',
       ' He’s a 9 but he uses “your” instead of “you’re”',
       ' He’s a 5 but he respects your boundaries',
       ' He’s a 9 but he does the wave at baseball games',
       ' He’s a 6 but he can hold really good conversations',
       ' He’s a 9 but he’s a SoundCloud rapper',
       ' He’s a 4 but he cares about your interests',
       ' He’s a 4 but he’s kind to animals',
       ' He’s a 6 but he’s always early',
       ' He’s a 9 but he’s a momma’s boy',
       ' He’s a 4 but he’s obsessed with you',
       ' He’s a 9 but he always wears flip flops',
       ' He’s a 9 but he only texts you after 11 pm',
       ' He’s an 8 but he dances on TikTok',
       ' He’s a 7 but gets jealous easily',
       ' He’s an 8 but doesn’t respect other people’s things',
       ' He’s a 4 but he takes amazing pictures of you',
       ' He’s a 10 but he doesn’t use deodorant',
       ' He’s a 4 but he can cook',
       ' He’s a 4 but he’s your age and on your flight',
       ' He’s a 6 but he only has eyes for you',
       ' He’s a 4 but he pays for everything',
       ' He’s a 2 but he has a really nice smile',
       ' He’s a 10 but he only showers once a week',
       ' He’s an 8 but wants an open relationship',
       ' He’s a 2 but he’s rich',
       ' He’s a 10 but gets stuck in a revolving door',
       ' He’s a 10 but he constantly talks bad about other people',
       ' He’s a 5 but he’s really protective of you',
       ' He’s a 5 but he’s funny',
       ' He’s a 4 but he’s loyal',
       ' He’s a 4 but he has the same interests as you',
       ' He’s a 5 but he understands your sarcasm and plays along',
       ' He’s 4 but has great style',
       ' He’s a 3 but he’s 6’5',
       ' He’s a 4 but he buys you flowers without you asking',
       ' He’s a 10 but replies once every 2-3 business days',
       ' He’s a 4 but he’s smart',
       ' He’s a 3 but he has a dog',
       ' He’s a 10 but he’s dumb',
       ' He’s a 10 but his driving gives you anxiety',
       ' He’s a 10 but he’s too friendly with other girls',
]
    let rand = Math.floor(Math.random()*texts.length);
    let randomText =texts[rand]
    console.log(randomText);
    i++;
    
        let displayText = document.querySelector('.random-text');
        displayText.innerHTML=randomText;   

    let displaycount = document.querySelector('.count');
    displaycount.innerHTML=i;
})